services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - 8080:8080
    environment:
      - SQLD_NODE=primary
    volumes:
      - libsql:/var/lib/sqld
  
  quick-share:
    image: ghcr.io/j4n-e4t/quick-share:latest
    ports:
      - 3000:3000
    environment:
      - TURSO_DATABASE_URL=http://db:8080
      - TURSO_AUTH_TOKEN=1233 # doesn't matter in docker install
      - ENCRYPTION_KEY= # openssl rand -hex 32
      - BASIC_AUTH_USERNAME=quick # use something else
      - BASIC_AUTH_PASSWORD=share # use something else
    depends_on:
      - db
volumes:
  libsql: